apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: prod project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  creationTimestamp: null
  name: prod
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: apps/**/envs/values-prod.yaml
      repoURL: https://github.com/egrau-hpg/gitops-workloads-demo.git
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
          source:
            repoURL: ""
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ path[1] }}'
      name: prod-{{ path[1] }}
      namespace: argocd
    spec:
      project: prod
      destination:
        namespace: 'prod'
        server: 'https://kubernetes.default.svc'
      source:
        repoURL: https://github.com/egrau-hpg/gitops-workloads-demo.git
        path: '{{ path }}/../chart'
        targetRevision: 'main'
        helm:
          valueFiles:
            - '../envs/values-prod.yaml'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
